GET http://localhost:2045/books

###
GET http://localhost:2045/books/65650dbc2509086479eeb6fa

###
POST http://localhost:2045/books
Content-Type: application/json

{
    "title": "The Catcher in the Rye",
    "author": "J.D. Salinger",
    "isbn" : 2390, 
    "url" : "https://www.google.com/",
    "summary" : "romance"
    
}

###
PATCH http://localhost:2045/books/65650dbc2509086479eeb6fa
Content-Type: application/json

{
    "title": "LIVRE DE FDP",
    "author": "J.D. Salinger",
    "isbn" : 2390, 
    "url" : "https://www.google.com/",
    "summary" : "romance"
    
}

###
DELETE http://localhost:2045/books/65650dbc2509086479eeb6fa